### PR TITLE
[WIP] Updated ReactJS to v.16.1.0

### PR DESCRIPTION
**Pull request by sunpietro**
Updated ReactJS to v.16.1.0

### CODE REVIEW

**Comment by dew326** [comment]
The name od React file should be updated in admin-ui

**Comment by sunpietro** [comment]
Closing as AlloyEditor doesn't support ReactJS 16 as reported there: https://github.com/liferay/alloy-editor/issues/807

**Comment by andrerom** [comment]
Is alloy 1.5[.1] (the version that was supposed to fix React 1.6 support), being used?

**Comment by sunpietro** [comment]
@andrerom it was mentioned in the release notes of 1.5.0: `Implemented enhancements/Fixed bugs: Alloy Editor crashes on React 16`

**Pull request closed without merging**
