### PR TITLE
Update Bootstrap and jQuery

### PR DESCRIPTION
**Pull request by glye**
To be determined if these changes are compatible.

### CODE REVIEW

**Review by dew326 — APPROVED** [review]

**Comment by glye** [comment]
@dew326 What is needed to bring this forwards? Do we need more reviews, or can I send to QA?

**Comment by dew326** [comment]
I think it is ok to send it to the QA

**Review by kacper-wieczorek-ibexa — APPROVED** [review]
QA - approved on 2.5.18

**Comment by dew326** [comment]
Please do not merge, this PR must be tested in a different way.

**Comment by dew326** [comment]
Here is a branch with installed dependencies for testing:
https://github.com/dew326/ezplatform-admin-ui-assets/tree/update-bs-jq-installed

To verify if everything is fine, please go to the browser, open console, and check the version of jQuery by "jQuery().jquery" it should return "3.5.1" (without this branch the same command should return "3.4.1").

**Comment by glye** [comment]
@dew326 @kacper-wieczorek-ibexa QA reports this as approved a week ago. Was that using the branch in the previous comment? Are we in sync or talking past each other? :)

**Review by kacper-wieczorek-ibexa — COMMENTED** [review]
@glye Yes, I used branch above. :)

**Comment by glye** [comment]
Merged. @dew326 could you please have a look at the merge up to master? Should we even do that? Master already has the same versions, and there are other not-yet-upmerged commits I'm not sure about.

**Comment by dew326** [comment]
It should be merged up. I will look at this.

**Comment by lserwatka** [comment]
@dew326 we need to make a new release on assets repo. Minor release

**Comment by dew326** [comment]
Yes, I will create 4.2.2.

**Comment by dew326** [comment]
Tag created: https://github.com/ezsystems/ezplatform-admin-ui-assets/tree/v4.2.2

**Pull request merged**
